### ISSUE TITLE
When PDF is loaded the program is stuck.

### ISSUE THREAD

**Issue by dustin2551** [EswarDivi/DocuConverse#2]
I load a few PDFs and the program is stuck. How long does it take for it to process a file? Any Guideline for a 1MB file to 20MB file?

**Comment by EswarDivi** [comment]
## I load a few PDFs and the program is stuck.

Is this program a [Streamlit App](https://chatwithpdf.streamlit.app/)? There is a chance it might break due to limited compute and storage resources. For uninterrupted use, please utilize the [HuggingFace Hosted App](https://huggingface.co/spaces/eswardivi/ChatwithPdf), where you can use your own Cohere [API](https://dashboard.cohere.com/api-keys) key, and it is free.


## How long does it take for it to process a file? Any guidelines for a 1MB file to a 20MB file?

It won't take much time.


I hope I have provided a helpful answer. Feel free to respond if there is anything else.

**Comment by dustin2551** [comment]
Thank you makes sense.
